### ISSUE TITLE
We havn't beer in the fridge [example issue]

### ISSUE THREAD

**Issue by cpalosrejano** [alvaromlg/narwhals#2]
U drunk last beer while you was fixing code in Python.
Please, refill the fridge of cool beer.
Link of fridge: http://electroportunidad.es/548-thickbox_default/frigorifico-benavent-bf2p144w.jpg
Thx.

 
PD: this is an example of issue.

**Comment by alvaromlg** [comment]
The fridge is full now https://cbsdallas.files.wordpress.com/2012/03/beer-fridge-3-e1333134090312.jpg
